### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by codingquark** [geminilabs/elixir-jshint#2]
Here is my gulpfile:

```
var elixir = require('laravel-elixir');
var gulp = require('gulp');
var handlebars = require('gulp-handlebars');
var wrap = require('gulp-wrap');
var declare = require('gulp-declare');
var concat = require('gulp-concat');
require('elixir-jshint');

elixir(function(mix) {
  mix.sass('app.scss')
    .jshint(['public/js/**/*.js']);
});
```

Upon running `gulp` I get the following error:

```
TypeError: undefined is not a function
    at Object.jshint (/node_modules/elixir-jshint/index.js:17:17)
    at gulp.task.gulp.src.pipe.pipe.pipe.declare.namespace (gulpfile.js:21:6)
    at Elixir (node_modules/laravel-elixir/index.js:3:5)
    at Object.<anonymous> (gulpfile.js:19:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

Am I missing something?

**Comment by pryley** [comment]
I can't reproduce this.
Make sure you are using the latest version of laravel-elixir (^6.0.0)
